### PR TITLE
Supply `name` and `target_commitish` for GitHub release

### PR DESCRIPTION
**Pull request by dgreif**

### CODE REVIEW

**Comment by stevemao** [comment]
hm... why would you wanna config those... it encourages manually release which is something you could do afterwards.

**Comment by dgreif** [comment]
I'm using the github release api to create the tag for me, rather than tagging and pushing before calling the api.  I need to set the properties so that github knows what commit and tag to create the tag with.

**Comment by hbetts** [comment]
@dgreif my understanding was the `conventional-github-releaser` creates a new tag for you, using the latest commit in the master branch as the target commit. Is that not the behavior you want?

In `conventional-gitlab-releaser` we actually have to specify the target commit (it's a requirement of the API), though we use `chunk.keyCommit.hash` for the commit to target - https://gitlab.com/hutson/conventional-gitlab-releaser/blob/687fc3f1b353e117dcb49bdb3f2c32b2adf02131/index.js#L80

**Comment by dgreif** [comment]
It's been a while since I looked at this, but I think we are in a unique situation.  We use our `dev` branch as our default branch in github, and reserve `master` specifically for prod deployments.  I think the issue we ran into was if we didn't merge every commit from `dev` into `master`, it would mark the release at the latest commit in `dev`, rather than what was actually deployed in `master`.

**Comment by dgreif** [comment]
The other part of our release process that is slightly unique is that we don't have any additional commit when we do a release.  Our repo is not published on npm, so we don't update the version number in the `package.json`, and we maintain our changelog in GitHub Releases rather than a `CHANGELOG.md` file.  A release for us just means a tag at master HEAD and a GitHub Release.

**Comment by hbetts** [comment]
Your unique release process is actually the standard process for how I manage my own projects on GitLab using `semantic-release-gitlab`, so it's actually a common process to me. (Though I still publish to npm, I just don't have a dedicated commit for bumping the `package.json` version)

So you want to generate releases on your non-default branch. That would require, as you've already noted, specifing the commit hash or branch name, as otherwise, GitHub will default to your default branch, as per the [documentation](https://developer.github.com/v3/repos/releases/#create-a-release)

So the change to specify the commit hash seems fine with me. It would basically support the existing behavior, while allowing your particular workflow.

:+1:

**Comment by dgreif** [comment]
Glad to hear we are on the same page 😄.  Anything need to be done with this PR to get it merged @stevemao?

**Comment by stevemao** [comment]
I guess just adding a test if possible?

**Comment by dgreif** [comment]
I would love to add a test, but I can't get the build to pass locally.  Looks like master is broken on TravisCI as well, but I can't access the travis build to see what's failing...

**Comment by hbetts** [comment]
@stevemao would you be able to correct the issue effecting the build? (Setting up an oauth token - `OAuth2 authentication requires a token or key & secret to be set`).

Also, once that's corrected, I think we can just push this pull request to the repo as a new branch, and that branch should have access to the encrypted environment variables. That should allow the branch to pass the tests. Once those tests pass, we can accept this pull request.

**Comment by stevemao** [comment]
The token should be correct. I haven't touched it for a while but it was working.

**Comment by hbetts** [comment]
Once we accept #33 and get our CI tests working again, I plan on pulling this branch into the repo as its own branch and then submitting a pull request to get a valid, and hopefully working, CI test.

**Comment by hbetts** [comment]
I've filed #36 to allow this change to run against our end-to-end tests on Travis-CI.

@dgreif thank you for your patience on this pull request. As soon as #36 builds successfully, I'll accept that pull request.

**Comment by dgreif** [comment]
Thanks for following through on this @hbetts!

**Pull request closed without merging**
