### PR TITLE
Revert "chore(deps): update"

### PR DESCRIPTION
**Pull request by hbetts**
This reverts commit ade480ef88f4ac43b973493a7bfa3ab7547884d7.

### CODE REVIEW

**Comment by hbetts** [comment]
@stevemao I submitted a revert of your dependency upgrades so that I could get the build green again.

My hope is to get the master branch build green again, and then move forward with accepting pull requests as I get their builds green.

**Comment by stevemao** [comment]
@hbetts Thanks for figuring it out! If you have time, could you fix it instead of reverting the commit? Cheers :)

**Comment by stevemao** [comment]
@hbetts It was just my idea. But please go ahead and do whatever you think is right :)

**Comment by stevemao** [comment]
nit: the commit message isn't right, it should be "revert: chore(deps): update". see [this](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#revert).

**Comment by hbetts** [comment]
@stevemao thank you for reminding me of the `revert` syntax.

Once I have the time to move forward with getting in all the pull requests submitted by people, I'd like to then go back and start upgrading each individual outdated dependency.

**Pull request merged**
